In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_train = pd.read_csv("./datasets/Doceree-HCP_Train.csv", encoding="latin-1")
df_train.head()

ID DEVICETYPE  PLATFORM_ID    BIDREQUESTIP  \
0  1001    Desktop            2    170.173.0.22   
1  1002    Desktop            2   65.216.253.25   
2  1003    Desktop            2    66.232.79.22   
3  1004    Desktop            3  137.54.125.246   
4  1005     Mobile            7  174.202.231.99   

                        USERPLATFORMUID     USERCITY  USERZIPCODE  \
0  6974dcaa-f932-480e-9fb5-c52e20e1393a     Portland      97206.0   
1  c12f3f8f-8fcf-484a-90e1-1ac04db8cdcf    Arlington      22202.0   
2  a698de4b-e200-46dd-b5fb-40402175ae18  New Meadows      83654.0   
3  45967533-75c8-4fbd-a00c-e6ff20447aaa          NaN  229114624.0   
4  a17e25be-532d-4cf5-b916-9308c8c3961f      Houston      77008.0   

                                           USERAGENT            PLATFORMTYPE  \
0  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  Online Medical Journal   
1  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  Online Medical Journal   
2  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  Online Medical Journal   
3  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  Online Medical Journal   
4  Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like...  Online Medical Journal   

  CHANNELTYPE                                                URL  \
0     Website  https://www.cancertherapyadvisor.com/home/canc...   
1     Website  https://www.cancertherapyadvisor.com/home/deci...   
2     Website  https://www.cancertherapyadvisor.com/home/canc...   
3     Website  https://globalrph.com/medcalcs/warfarin-mainte...   
4     Website  https://www.cureus.com/articles/58184-a-review...   

                                            KEYWORDS    TAXONOMY  IS_HCP  
0  General|Endocrine|False|Medicine|Surgery|Urolo...         NaN     0.0  
1  Bone Marrow|Radiography|Chronic|Oncology|Psych...         NaN     0.0  
2  General|Endocrine|False|Medicine|Surgery|Urolo...         NaN     0.0  
3  Dental|Total|Clinical|Pharmacology|Physicians|...  2084P0800X     1.0  
4  Critical Care|Emergency Medicine|General Pract...         NaN     0.0

In [3]:
df_train.drop(columns=["ID", "BIDREQUESTIP", "USERPLATFORMUID", "USERCITY", "USERZIPCODE", "USERAGENT", "CHANNELTYPE", "URL", "KEYWORDS", "TAXONOMY"], inplace=True)

In [4]:
df_train

DEVICETYPE  PLATFORM_ID            PLATFORMTYPE  IS_HCP
0         Desktop            2  Online Medical Journal     0.0
1         Desktop            2  Online Medical Journal     0.0
2         Desktop            2  Online Medical Journal     0.0
3         Desktop            3  Online Medical Journal     1.0
4          Mobile            7  Online Medical Journal     0.0
...           ...          ...                     ...     ...
113932    Desktop            2  Online Medical Journal     1.0
113933    Desktop            2  Online Medical Journal     1.0
113934    Desktop            7  Online Medical Journal     1.0
113935     Mobile            2  Online Medical Journal     1.0
113936     Mobile            2  Online Medical Journal     1.0

[113937 rows x 4 columns]

In [5]:
df_train.isna().sum()

DEVICETYPE      0
PLATFORM_ID     0
PLATFORMTYPE    0
IS_HCP          1
dtype: int64

In [6]:
df_train.dropna(axis=0, subset=["IS_HCP"], inplace=True)

In [7]:
x = df_train.iloc[: , :-1]
y = df_train.iloc[:, -1]

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), ["DEVICETYPE", "PLATFORMTYPE"])], remainder="passthrough")
x = ct.fit_transform(x)

In [9]:
y = y.astype('int').values

In [10]:
x

array([[1., 0., 0., ..., 1., 0., 2.],
       [1., 0., 0., ..., 1., 0., 2.],
       [1., 0., 0., ..., 1., 0., 2.],
       ...,
       [1., 0., 0., ..., 1., 0., 7.],
       [0., 1., 0., ..., 1., 0., 2.],
       [0., 1., 0., ..., 1., 0., 2.]])

In [11]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [12]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x, y)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [13]:
df_test = pd.read_csv("./datasets/Doceree-HCP-Test.csv", encoding="latin-1")
df_test.head()

ID DEVICETYPE  PLATFORM_ID     BIDREQUESTIP  \
0  115501    Desktop          2.0   75.189.231.103   
1  115502     Mobile          2.0    24.101.33.158   
2  115503    Desktop          2.0  172.118.216.142   
3  115504    Desktop          7.0   71.105.120.171   
4  115505    Desktop          2.0     73.82.211.73   

                        USERPLATFORMUID       USERCITY  USERZIPCODE  \
0  0d5041ff-f0b6-4d1a-9ad7-0a29f7d485b4   Fayetteville      28305.0   
1  c8396dd0-969f-4d99-a40b-b7bb1f516154  Conneaut Lake      16316.0   
2  3c97a081-6518-43f8-9f26-369759cfb471         Covina      91724.0   
3  3e2578c8-f794-41af-a38c-c5cfb3c0f014       Brooklyn      11226.0   
4  ec2ae7ce-6a8c-4156-98a7-07203e60f483       Marietta      30062.0   

                                           USERAGENT            PLATFORMTYPE  \
0  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6...  Online Medical Journal   
1  Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like...  Online Medical Journal   
2  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  Online Medical Journal   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  Online Medical Journal   
4  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  Online Medical Journal   

  CHANNELTYPE                                                URL  \
0     Website  https://www.clinicaladvisor.com/home/features/...   
1     Website  https://www.ophthalmologyadvisor.com/topics/ca...   
2     Website  https://www.psychiatryadvisor.com/author/tori-...   
3     Website  https://www.cureus.com/articles/105482-diverti...   
4     Website  https://www.renalandurologynews.com/home/confe...   

                                            KEYWORDS  
0  Family Practice|Drainage|Clinical|Dermatology|...  
1  General|Clinical|Operative|Medicine|Cardiology...  
2  Abortion|Anxiety Disorders|Apnea|False|Trauma|...  
3  Health|Male|Neurological Surgery|Otolaryngolog...  
4  chronic kidney disease|pain|nephrology|disease...

In [14]:
df_test.drop(columns=["ID", "BIDREQUESTIP", "USERPLATFORMUID", "USERCITY", "USERZIPCODE", "USERAGENT", "CHANNELTYPE", "URL", "KEYWORDS"], inplace=True)

In [15]:
df_test.head()

DEVICETYPE  PLATFORM_ID            PLATFORMTYPE
0    Desktop          2.0  Online Medical Journal
1     Mobile          2.0  Online Medical Journal
2    Desktop          2.0  Online Medical Journal
3    Desktop          7.0  Online Medical Journal
4    Desktop          2.0  Online Medical Journal

In [16]:
df_test.isna().sum()

DEVICETYPE      30
PLATFORM_ID     50
PLATFORMTYPE    50
dtype: int64

In [17]:
df_test.dropna(inplace=True)

In [18]:
x_test = df_test.iloc[: , :]

In [19]:
x_test

DEVICETYPE  PLATFORM_ID            PLATFORMTYPE
0        Desktop          2.0  Online Medical Journal
1         Mobile          2.0  Online Medical Journal
2        Desktop          2.0  Online Medical Journal
3        Desktop          7.0  Online Medical Journal
4        Desktop          2.0  Online Medical Journal
...          ...          ...                     ...
28575    Desktop          2.0  Online Medical Journal
28576    Desktop          7.0  Online Medical Journal
28577    Desktop          7.0  Online Medical Journal
28578    Desktop          8.0  Online Medical Journal
28579    Desktop          2.0  Online Medical Journal

[28530 rows x 3 columns]

In [20]:
x_test = ct.transform(x_test)

In [21]:
x_test

array([[1., 0., 0., ..., 1., 0., 2.],
       [0., 1., 0., ..., 1., 0., 2.],
       [1., 0., 0., ..., 1., 0., 2.],
       ...,
       [1., 0., 0., ..., 1., 0., 7.],
       [1., 0., 0., ..., 1., 0., 8.],
       [1., 0., 0., ..., 1., 0., 2.]])

In [22]:
y_pred = classifier.predict(x_test)

In [23]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
df_pred = pd.read_csv("./datasets/Doceree_HCP_Sample_Submission_1.csv")
df_pred.head()

ID    TAXONOMY  IS_HCP
0   1         NaN       0
1   2  2084P0800X       1
2   3         NaN       0
3   4         NaN       0
4   5         NaN       0

In [ ]:
df_pred.isna

In [24]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y.reshape(len(y),1)),1))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 28530 and the array at index 1 has size 113936

In [25]:
# accuracy score
from sklearn.metrics import accuracy_score
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

In [26]:
accuracy_score(y, y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [113936, 28530]

In [ ]:
confusion_matrix(y, y_pred)

In [ ]:
disp = ConfusionMatrixDisplay(confusion_matrix=confusion_matrix(y, y_pred))
disp.plot()

In [ ]:
# Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
classifier2 = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier2.fit(X=x, y=y)

In [ ]:
descision_tree_pred = classifier2.predict(x_test)

In [ ]:
accuracy_score(y, descision_tree_pred)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier3 = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
classifier3.fit(x, y)

In [ ]:
knn_ypred = classifier3.predict(x_test)

In [ ]:
accuracy_score(y, knn_ypred)

In [ ]:
from sklearn.svm import SVC
classifier4 = SVC(kernel='linear', random_state=0)
classifier4.fit(x, y)

In [27]:
new_df = pd.read_csv("./datasets/Doceree_HCP_Sample_Submission_1.csv")
new_df

ID    TAXONOMY  IS_HCP
0          1         NaN       0
1          2  2084P0800X       1
2          3         NaN       0
3          4         NaN       0
4          5         NaN       0
...      ...         ...     ...
28525  28526         NaN       0
28526  28527         NaN       0
28527  28528         NaN       0
28528  28529         NaN       0
28529  28530         NaN       0

[28530 rows x 3 columns]